---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.commonSecrets.name" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.commonSecrets }}
  {{ $key }}: {{ quote $value }}
  {{- end }}
