{{- if .Values.ingress.tls.enabled }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.tls.name" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}
{{- end }}
