---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.webserver.name" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: webserver
  annotations:
    {{- include "airflow.checksum" . | nindent 4 }}
spec:
  replicas: {{ .Values.webserver.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "airflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webserver
  template:
    metadata:
      labels:
        {{- include "airflow.labels" . | nindent 8 }}
        app.kubernetes.io/component: webserver
      annotations:
        {{- include "airflow.checksum" . | nindent 8 }}
    spec:
      containers:
      - name: webserver
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
        - webserver
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 443
        securityContext:
          {{- include "airflow.securityContext" (dict "userID" 50000 "groupID" 0) | nindent 10 }}
        envFrom:
          {{- include "airflow.commonSecrets.env" . | nindent 8 }}
        {{- include "airflow.probes" (dict "path" "/health" "port" "http" "probeType" "httpGet") | nindent 8 }}
        volumeMounts:
        {{- include "airflow.home.volumeMount" . | nindent 8 }}
      volumes:
      {{- include "airflow.home.pvc" . | nindent 6 }}
