{{- if .Values.ingress.enabled }}
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "airflow.webserver.name" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: webserver-ingress
  {{- if .Values.ingress.tls.enabled }}
  annotations:
    {{- include "airflow.ingress.checksum" . | nindent 4 }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "airflow.tls.name" . }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.webserver.urlPrefix }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "airflow.webserver.name" . }}
            port:
              name: http
{{- end }}
