{{- if and .Values.ingress.enabled .Values.flower.enabled }}
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "airflow.flower.name" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: flower-ingress
  annotations:
    {{- if .Values.ingress.tls.enabled }}
      {{- include "airflow.ingress.checksum" . | nindent 4 }}
    {{- end }}
    {{- toYaml .Values.ingress.flower.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "airflow.tls.name" . }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.flower.urlPrefix | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "airflow.flower.name" . }}
            port:
              name: flower
{{- end }}
