---

apiVersion: v2
name: airflow
description: A Helm chart for kick starting your development in Cohesive Build.

type: application
version: 2.2.2
appVersion: "2.2.2"

dependencies:
  - name: postgresql
    alias: pg
    version: "14.0.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: pg.enabled

  - name: redis
    alias: redis
    version: "18.12.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
