apiVersion: v2
name: airflow
description: A Helm chart for Kubernetes

type: application
version: 0.2.1
appVersion: "0.2.0"

dependencies:
  - name: postgresql
    alias: pg
    version: "14.0.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: pg.enabled

  - name: redis
    alias: redis
    version: "18.12.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
